README.md
docs/README_Kor.md
requirements.txt
setup.py
src/fosslight_source/_timer_thread.py
src/fosslight_source/run_scancode.py

Add a spinner when scanning

---

README.md
docs/README_Kor.md
setup.py
src/fosslight_source/convert_scancode.py
src/fosslight_source/run_scancode.py

(Please describe what this PR do.)

Sort by license

---

.reuse/dep5
LICENSES/Apache-2.0.txt
README.md
tox.ini

Add files for reuse compliance.

Add files for reuse compliance

---

README.md
docs/README_Kor.md

Add a reuse badge

---

requirements.txt

Remove click from requirement.txt.

Remove click from requirement.txt

---

tox.ini

Delete unnecessary lines at tox.ini

Delete unnecessary lines at tox.ini

---

.github/workflows/pull-request.yml

Add reuse compliance checking to PR action.

Add reuse compliance checking

---

LICENSES/LicenseRef-MIT-like.txt
src/fosslight_source/_parsing_scancode_file_item.py
src/fosslight_source/run_scancode.py
tests/cli_test.py
tests/test_files/test_known_spdx.txt
tests/test_files/test_unknown_spdx.txt

Print the matched text for unknown spdx

Print the matched text for unknown spdx

---

.github/workflows/publish-release.yml

Remove warning in publish-release.yml

Remove warning in publish-release.yml

---

.github/workflows/publish-release.yml

Fix a bug related Release actions.
Checkout to main branch when deploy it.

Fix a bug related Release actions

---

requirements.txt
src/fosslight_source/_help.py

Add the m option to help message.

 Set condition to use FOSSLight Util v1.1.0 or later

---

src/fosslight_source/_license_matched.py

Remove duplicates from matched file.

Remove duplicates from matched file

---

requirements.txt

Update required version of fosslight_util

Update required version of fosslight_util

---

README.md

Fix broken url for User Guide in READEME.md

Fix url for User Guide

---

.github/workflows/pull-request.yml
tox.ini

Add python version to github PR action

Add python version to github PR action

---

setup.py
src/fosslight_source/_help.py
src/fosslight_source/_parsing_scancode_file_item.py
src/fosslight_source/_parsing_scanoss_file.py
src/fosslight_source/_scan_item.py
src/fosslight_source/cli.py
src/fosslight_source/run_scancode.py
src/fosslight_source/run_scanoss.py
tests/cli_test.py

Add scanoss.py as a scanner.
Separate common codes for scanning.

Add scanoss.py as a scanner

---

requirements-dev.txt
src/fosslight_source/run_scanoss.py
tests/test_files/run_scancode.py
tox.ini

1. Add scanoss thread feature for faster scanoss scanning process
2. Amend tox.ini to check result files by scanning options

Add scanoss thread feature and amend tox test

---

requirements.txt
src/fosslight_source/cli.py
src/fosslight_source/run_scancode.py

- Adopt change of FOSSLight Util to print output file name.
- Fix to handle wrongly inputted format and output option.

Amend to print output file name and deal with format option error

---

setup.py
src/fosslight_source/_parsing_scancode_file_item.py
src/fosslight_source/_parsing_scanoss_file.py
src/fosslight_source/run_scancode.py
src/fosslight_source/run_scanoss.py
tests/test_files/run_scancode.py

- When installing scanoss in python 3.6, there is an additional package to install.
- Apply f-string format.

Change the scanoss-related packages

---

src/fosslight_source/_parsing_scanoss_file.py

Refine license name on SCANOSS results

Refine license name on SCANOSS results

---

src/fosslight_source/_help.py
src/fosslight_source/cli.py
src/fosslight_source/run_scancode.py

Signed-off-by: Jiyeong Seok <jiyeong.seok@lge.com>
Add yaml format for FOSSLight Report

Add yaml format for FOSSLight Report

---

requirements.txt

Signed-off-by: Jiyeong Seok <jiyeong.seok@lge.com>
update minimum version of fosslight_util

update minimum version of fosslight_util

---

src/fosslight_source/convert_scancode.py
tests/scancode_raw.json
tox.ini

Fix the bug that convert mode does not run

Fix the bug that convert mode does not run

---

src/fosslight_source/_parsing_scancode_file_item.py
src/fosslight_source/cli.py
src/fosslight_source/convert_scancode.py

Print the message if there is nothing to print.

Print the message if there is nothing to print

---

src/fosslight_source/cli.py
src/fosslight_source/convert_scancode.py

If the path input with -p is null, analyze the path where the command was executed.

Analyze the current path if path is null

---

src/fosslight_source/cli.py

Print tool information to log. 
- ex. Log file
- AS-IS: 
```
[   INFO] Output Directory: /home/soimkim/git/latest/fosslight_source_scanner
Parsing Log: 
Scan Result: 'True'
[   INFO] |---Number of files detected with SCANOSS: 1
[  DEBUG] ITEM COUNT:7
[   INFO] Output file:/home/soimkim/git/latest/fosslight_source_scanner/FOSSLight-Report_20220804_211618.xlsx
``` 
- TO-BE:
```
[   INFO] Output Directory: /home/soimkim/git/latest/fosslight_source_scanner
Parsing Log: 
Scan Result: 'True'
[   INFO] |---Number of files detected with SCANOSS: 1
[  DEBUG] ITEM COUNT:7
[   INFO] Output file:/home/soimkim/git/latest/fosslight_source_scanner/FOSSLight-Report_20220804_211618.xlsx
[   INFO] OS: Linux 4.15.0-189-generic
Path to analyze: tests/test_files
Python version: 3
Scan Result: 'True'
Tool …
```

Print tool information to log

---

src/fosslight_source/_parsing_scancode_file_item.py

Fix the bug that can't extract copyright.

Fix the bug that can't extract copyright

---

src/fosslight_source/cli.py

Block -m option for opossum,yaml and csv.

Block -m option for opossum,yaml and csv

---

setup.py

Clear ScanCode cache after installation. 
- Related Issue : https://github.com/nexB/scancode-toolkit/issues/3179

Clear ScanCode cache after installation

---

requirements.txt

This reverts commit bf0f9dadbf13d0bf5ba91c66e2221c38a184e88c.
Bug fixed : https://github.com/nexB/scancode-toolkit/issues/3171

Revert "Fix ScanCode's import LegacyVersion bug"

---

src/fosslight_source/cli.py

Remove warning for -m option with default output

Remove warning for -m option with default output

---

src/fosslight_source/_parsing_scancode_file_item.py

Remove warranty-disclaimer from license detected by ScanCode.

Remove warranty-disclaimer from license detected by ScanCode

---

src/fosslight_source/_parsing_scanoss_file.py

Fix omitted Scanoss result at -m option

Fix omitted Scanoss result at -m option

---

src/fosslight_source/_help.py

Unify version output format

---

src/fosslight_source/convert_scancode.py
src/fosslight_source/run_scancode.py
src/fosslight_source/run_scanoss.py

Add the package name to log and result file

Add the package name to log and result file

---

.github/workflows/publish-release.yml

- Update git user in release action

Update git user in release action

---

.bumpversion.cfg
.github/workflows/publish-release.yml
setup.py

Update the ubuntu version for deploy action

Update the ubuntu version for deploy action

---

requirements.txt

Update the minimum version of util

Update the minimum version of util

---

requirements.txt

- Update FL util minimum version to fix the following bugs.
https://github.com/fosslight/fosslight_util/pull/124

Update FOSSLight Util version

---

requirements.txt

Update scancode-toolkit version

Update scancode-toolkit version

---

src/fosslight_source/cli.py

- Remove sorting by files, since it is done at the FOSSLight util now.

Remove sorting

---

requirements.txt

Revert the scancode-toolkit version

Revert the scancode-toolkit version

---

requirements.txt

Fix the util version

---

requirements.txt

Fix the scancdoe and util version

Fix the scancdoe and util version

---

src/fosslight_source/_parsing_scancode_file_item.py

Fix the bug when nothing is detected.

Fix the bug when nothing is detected

---

requirements.txt

Fix vulnerability issue

---

tox.ini

Amend tox.ini to add test for FOSSLight Scanner and FOSSLight Android Scanner

Add test for fl scanner and fl android

---

.github/workflows/pull-request.yml

ref #141 
ref https://github.com/fosslight/fosslight/pull/969#issue-1868493271
commit message checking workflow was separately defined on this project
uses commit message checking workflow from `.github` repository
- fetches `base-check-commit-message.yml` from `.github`

Fetch base-check-commit-message.yml from .github

---

requirements.txt
setup.py

Update python versions in setyp.py and requirements.txt

Upgrade minimum version of python to 3.8

---

src/fosslight_source/_scan_item.py

Merge copyright findings from each file with new lines

Merge copyrights with new line

---

tests/cli_test.py

Fix cli_test log path

---

requirements.txt
src/fosslight_source/_help.py
src/fosslight_source/_parsing_scanoss_file.py
src/fosslight_source/cli.py
src/fosslight_source/run_scancode.py
src/fosslight_source/run_scanoss.py
src/fosslight_source/run_spdx_extractor.py
tox.ini

* Supports for excluding paths.
* ScanOSS : Remove the scan result from the paths which needs to be excluded.
* ScanCode : Exclude analysis with the ignore option.

Supports for excluding paths

---

src/fosslight_source/_parsing_scanoss_file.py
src/fosslight_source/cli.py

- Modify column name
- 'Source Name or Path' -> 'Source Path'

Modify column name

---

src/fosslight_source/_scan_item.py

Move method to limit license characters.

Move method to limit license characters

---

src/fosslight_source/_scan_item.py

Bug fix related to license duplication.

Bug fix related to license duplication

---

requirements.txt

Upgrade ScanCode to be identical to the ScanCode version of FOSSLight Scanner Service.

Update scancode version for web service

---

src/fosslight_source/run_scancode.py
src/fosslight_source/run_scanoss.py

* Amend for excluding absolute paths
* Compatible with fosslight scanner

Amend exclude option

---

src/fosslight_source/_parsing_scancode_file_item.py

Fix SPDX expression split bug.

Fix SPDX expression split bug

---

requirements.txt

Update scancode version for mac

Update scancode version for mac

---

src/fosslight_source/_parsing_scancode_file_item.py

Reverts fosslight/fosslight_source_scanner#165

Revert "Fix SPDX expression split bug"

---

src/fosslight_source/_parsing_scancode_file_item.py

Complying with SPDX License expression spec

Complying with SPDX License expression spec

---

requirements.txt

Version up FOSSLight util to 1.4.47 to fix default file bug

Version up FOSSLight util to fix default file bug

---

src/fosslight_source/run_scanoss.py

Add --ignore-cert-errors to ScanOSS command.

Add --ignore-cert-errors to ScanOSS command

---

src/fosslight_source/cli.py

Modify error comment

---

src/fosslight_source/_help.py
src/fosslight_source/_license_matched.py
src/fosslight_source/_parsing_scancode_file_item.py
src/fosslight_source/_parsing_scanoss_file.py
src/fosslight_source/_scan_item.py
src/fosslight_source/cli.py
src/fosslight_source/run_scancode.py
src/fosslight_source/run_scanoss.py
src/fosslight_source/run_spdx_extractor.py
tox.ini

Add type hint about fosslight_source_scanner's functions.

Add type hint

---

src/fosslight_source/cli.py

Fix the cover_comment

---

requirements.txt
src/fosslight_source/cli.py

Support cycloneDX format

---

src/fosslight_source/cli.py

Fix the bug

---

requirements.txt

Fix scancode copyright scanning error.
(ref: https://github.com/aboutcode-org/scancode-toolkit/issues/4129)

Fix scancode copyright scanning err

---

src/fosslight_source/_parsing_scancode_file_item.py
src/fosslight_source/_scan_item.py

Recognize manifest file as License File

Recognize manifest file as License File

---

src/fosslight_source/_parsing_scancode_file_item.py
tests/test_tox.py

Remove copyright info for license text file of GPL family

Remove copyright info for license text file of GPL family
