fosslight/fosslight_source_scanner

requirements.txt
setup.py
src/fosslight_source/run_scancode.py
test/cli_test.py
tox.ini

(Please describe what this PR do.)

Add returning item parameter

---

README.md
docs/README_Kor.md
src/fosslight_source/_help.py
src/fosslight_source/convert_scancode.py
src/fosslight_source/run_scancode.py
tests/cli_test.py
tox.ini

Modify tox.ini to separate release test from normal test
Change OSS report name to FOSSLight report

Change OSS report name to FOSSLight report

---

src/fosslight_source/convert_scancode.py
src/fosslight_source/run_scancode.py
tests/cli_test.py
tox.ini

Merge init_log & init_log_item functions

Merge init_log & init_log_item functions

---

src/fosslight_source/_license_matched.py
src/fosslight_source/_parsing_scancode_file_item.py
src/fosslight_source/convert_scancode.py
src/fosslight_source/run_scancode.py
tox.ini

When running, adding the -m option adds a sheet called **matched_text** to the output spreadsheet.
ex) matched_text sheet :
Category | License | Matched Text | File Count | Files
-- | -- | -- | -- | --
Copyleft | GPL-2.0 | GPL licensed | 2 | test/a, test/b

Add option for printing matched text

---

src/fosslight_source/convert_scancode.py

Print help message when p option is missing.

Print help message when p option is missing

---

requirements.txt

The installed version of ScanCode is limited to version 21.3.31 or lower.
However, the package used for version 21.3.31 has been deleted recently, so it cannot be executed.
Therefore, the version restriction was removed so that ScanCode can be installed with the latest version.
- Error Message
```
File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "fosslight_source_scanner/.tox/test_run/lib/python3.6/site-packages/packagedcode/__init__.py", line 15, in <module>
from packagedcode import debian
File "fosslight_source_scanner/.tox/test_run/lib/python3.6/site-packages/packagedcode/debian.py", line 14, in <module>
from debut import debcon
ModuleNotFoundError: No module named 'debut'
```
Please insert 'x' …

Remove required version of ScanCode

---

.github/PULL_REQUEST_TEMPLATE.md
src/fosslight_source/convert_scancode.py
src/fosslight_source/run_scancode.py

- Update datetime format. 
- Update github PR template.

Update datetime format

---

.github/workflows/pull-request.yml
tox.ini

FOSSLight Source Scanner is going to have different packages that are additionally installed in python 3.6, 3.6 or later versions.
- Add Python 3.7 to your Python test.
- Remove basepython version from tox.

Add python version to github PR action

---

src/fosslight_source/_parsing_scanoss_file.py
src/fosslight_source/_scan_item.py

- Change only ScanCode to print comments.
- Store vendor, fileURL, matched_line in separate variables for Scanoss.

Change only ScanCode to print comments

---

requirements-dev.txt
src/fosslight_source/run_scanoss.py
tests/test_files/run_scancode.py
tox.ini

1. Add scanoss thread feature for faster scanoss scanning process
2. Amend tox.ini to check result files by scanning options
3. Add source file(tests/test_files/run_scancode.py) to check values from scanoss result

Add scanoss thread feature and amend tox test

---

src/fosslight_source/_scan_item.py
src/fosslight_source/cli.py

1. Add matched lines, fileURL, vendor information when printing a row
2. Remove additional information from SCANOSS scan when output format is set as Opossum report
3. Add extended_header and provide it when writing output file at FOSSlight util

Add scanoss information on excel

---

requirements.txt

- Installation error to fix: 
```
ERROR: Command errored out with exit status 1:
command: /home/worker/fosslight_source_scanner/venv38/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-7_f88644/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-7_f88644/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-af93bynu
cwd: /tmp/pip-req-build-7_f88644/
Complete output (6 lines):
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: setup.py --help [cmd1 cmd2 ...]
or: setup.py --help-commands
or: setup.py cmd --help
error: invalid command 'bdist_wheel' …
```

Add package to fix installation errors

---

README.md

Update README.md to add description for SCANOSS

Update README.md to add description for SCANOSS

---

requirements.txt
src/fosslight_source/_help.py
src/fosslight_source/cli.py
src/fosslight_source/convert_scancode.py

Add the v option to print the installed version of FOSSLight Source Scanner.

Add the -v option to print the installed version of FOSSLight Source Scanner

---

src/fosslight_source/_scan_item.py
src/fosslight_source/cli.py
src/fosslight_source/run_scanoss.py

Add "license_reference" column for excel output.
If both ScanCode and SCANOSS are run and;
if license findings from the scanners differ;
"license_reference" column will be filled with scanner name and scanned licenses respectively.

Add license reference column

---

setup.py

When installing scanoss in python 3.6,
dataclasses need to be installed additionally.

Change the scanoss-related packages

---

requirements.txt

Fix errors that occur in Python 3.6.7 or lower. 
- From version 3.0.6 of pyparsing (version conflict issue occurs when installing version 3.0.5), only Python 3.6.8+ is supported.
Therefore, in the case of Python 3.6.7 or earlier, modify pyparsing to install 3.0.4 or earlier.

Fix errors that occur in Python 3.6.7 or lower

---

Dockerfile
requirements.txt

Provide a Dockerfile to run fosslight_source in an unsupported OS environment such as mac m1.
How to run:
```
$docker build -t fosslight .
$docker run -it -v /Users/soim/git/fosslight_source_scanner/test_output:/app/output fosslight -p tests/test_files -o output
```

Add Dockerfile to build on ubuntu

---

src/fosslight_source/cli.py
src/fosslight_source/run_scanoss.py
tox.ini

- Fix cli.py to remove redundant report.
To fix the bug where the ScanCode result report is additionally generated, set the ScanCode Report not to be created separately by default.
- Fix the bug where ScanOSS output fails when the output directory does not exist.
- Make the tox command simple.

Fix cli.py to remove redundant report

---

src/fosslight_source/_help.py
src/fosslight_source/_parsing_scancode_file_item.py
src/fosslight_source/_parsing_scanoss_file.py
src/fosslight_source/_scan_item.py
src/fosslight_source/cli.py
src/fosslight_source/run_scanoss.py

- Moving SCANOSS reference information from main sheet to a separate sheet that is created with -m option. Before this PR is applied to the next release, we should discuss about the columns of the sheet and finalize the spec.
- Removing redundant output files cause by run_scancode while called as library.
Example of the output File
- SRC_FL_Source sheet
- scancode_reference sheet
- scanoss_reference sheet

Print SCANOSS info in a separate sheet

---

src/fosslight_source/cli.py
src/fosslight_source/run_scancode.py
src/fosslight_source/run_scanoss.py

- Handle path without files to scan when SCANOSS is on
- Handle path that doesn't exist when SCANOSS is on

Amend how to handle path without files to scan for SCANOSS

---

requirements.txt

Fix typecode-libmagic-from-sources installation bug.
```
note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure
× Encountered error while trying to install package.
╰─> typecode-libmagic-from-sources
```

Fix typecode-libmagic-from-sources installation bug

---

src/fosslight_source/_help.py
src/fosslight_source/cli.py
src/fosslight_source/run_scancode.py

`-t FLOAT`
- Stop scanning a file if scanning takes longer than a timeout in seconds. [Default: 120]

Add option for time out

---

Dockerfile

Fix the bug that the related package cannot be downloaded when installing with Docker.

Fix package download bug during docker build

---

src/fosslight_source/_help.py

Remove the required option from the help message

Remove the required option from the help message

---

src/fosslight_source/_parsing_scancode_file_item.py
tests/test_files/dual.txt
tests/test_files/spdx_lic.txt

- Fix a bug when loading a key that does not exist when parsing by item in the scancode analysis result.

Fix a bug when reading a non-existent key

---

src/fosslight_source/run_scancode.py

Do not print empty parsing messages.

Do not print empty parsing messages

---

src/fosslight_source/cli.py
src/fosslight_source/convert_scancode.py
src/fosslight_source/run_scancode.py
src/fosslight_source/run_scanoss.py
tests/cli_test.py
tests/test_files/run_scancode.py

Change the output file name

---

requirements-dev.txt
src/fosslight_source/cli.py

- Changed argument parsing for CLI from getopt to argparse
- Added importlib-metadata with specific version as a dependency for test on Python-3.7

Change argument parsing from getopt to argparse

---

src/fosslight_source/_parsing_scanoss_file.py

Remove the last dot from the result in scanoss license finding.
Example : Apache-2.0. -> Apache-2.0

Remove the last dot from the result in scanoss license finding

---

src/fosslight_source/convert_scancode.py

Change argument parsing for convert to argpars.

Change argument parsing for convert to argpars

---

src/fosslight_source/_help.py
src/fosslight_source/cli.py
src/fosslight_source/convert_scancode.py
tests/test_files/run_scancode.py

Unify help message for source scanner and converter

Unify help message for source scanner and converter

---

requirements.txt
src/fosslight_source/cli.py
tox.ini

1. Execute Scancode with multi-processing as many as the number of input cores.
- Default : Number of cores - 1
2. tox: Use allowlist_externals instead of whitelist_externals
- whitelist_externals is now deprecated, use allowlist_externals instead. see [https://tox.readthedocs.io/en/latest/config.html](https://tox.readthedocs.io/en/latest/config.html)
3. Fix ScanCode's import LegacyVersion bug by fixing [packaging ](https://pypi.org/project/packaging/#history)version.
- https://github.com/nexB/scancode-toolkit/issues/3171

Add parameter for Scancode cores

---

setup.py

Reverts fosslight/fosslight_source_scanner#101

Revert "Clear ScanCode cache after installation"

---

src/fosslight_source/_help.py

Add the core option in help message

Add the core option in help message

---

src/fosslight_source/cli.py
src/fosslight_source/convert_scancode.py
src/fosslight_source/run_scancode.py

Add the package name to result in the missing file

Add the package name to result in the missing file

---

setup.py

Fix Scancode error in Python 3.7.
- Error message : `ImportError: cannot import name 'TypedDict' from 'typing'`
- Related Issue : https://github.com/nexB/scancode-toolkit/issues/3246

Fix Scancode error in Python 3.7

---

LICENSES/MIT.txt
src/fosslight_source/_parsing_scancode_file_item.py
tests/test_files/sample.cpp
tests/test_files/temp.cpp

Remove SPDX, URL from copyright.
ex. 
Source file : 
```
/*
* SPDX-FileCopyrightText: Copyright 2022 LG Electronics Inc.
* SPDX-License-Identifier: Apache-2.0
* DownloadLocation: https://github.com/browserify/acorn-node
*/
```
Extracted copyright:
- AS-IS: `Copyright 2022 LG Electronics Inc. SPDX-License-Identifier Apache-2.0 DownloadLocation https://github.com/browserify/acorn-node`
- TO-BE: `Copyright 2022 LG Electronics Inc. `

Remove SPDX, URL from copyright

---

src/fosslight_source/_parsing_scanoss_file.py
src/fosslight_source/_scan_item.py

Remove empty values from SCANOSS reference sheet created with -m option.

Remove empty scanoss reference

---

requirements.txt
src/fosslight_source/_help.py
src/fosslight_source/cli.py
src/fosslight_source/run_scancode.py

Add to correct with sbom-info.yaml

Add to correct with sbom-info.yaml

---

src/fosslight_source/_license_matched.py
src/fosslight_source/_parsing_scancode_file_item.py
src/fosslight_source/_scan_item.py

Load v32 and later of ScanCode.

Load v32 and later of ScanCode

---

src/fosslight_source/_parsing_scancode_file_item.py
src/fosslight_source/_scan_item.py
src/fosslight_source/cli.py
src/fosslight_source/run_scancode.py
src/fosslight_source/run_spdx_extractor.py
tests/cli_test.py

Change download location extracting code ran independently from the scanners.
Now, download location with keyword "SPDX-PackageDownloadLocation" can be found
even if there are no scanner result for each source files.

Priority change between Download Location extraction and scanner operation

---

requirements.txt
src/fosslight_source/_scan_item.py
src/fosslight_source/cli.py
src/fosslight_source/run_scancode.py

- Create run_scanners so that FL Scanner can call via api
- Make value of Exclude column for binary and .m4 files as "Exclude"
- Remove deprecated code for correct mode

Create run_scanners for api and exclude unwanted outputs

---

Dockerfile
requirements.txt

ref #135 
Changed docker base image from `ubuntu:20.04` to `python:3.8-slim-buster`
Reduced the number of layers
Reduced 0.31GB of the image size
build time also decreased from 5.5 min to 2 min in my environment (Win10, i5-10400F, 16GB RAM)

Optimize Dockerfile to reduce image size

---

.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
src/fosslight_source/cli.py

- Prevent run_scanners from exiting without returning.
- Update python versions in github actions.

Modify run_scanners to return

---

requirements.txt

Change to the version of ScanCode that runs on mac ARM.
On Mac, the following warning message occurs because typecode-libmagic is not installed. (typecode-libmagic cannot be installed on Mac Arm)
- `UserWarning: Libmagic magic database not found. A default will be used if possible. Install instead a typecode-libmagic plugin for best support.
OR set the TYPECODE_LIBMAGIC_DB_PATH environment variable.
warnings.warn(
`

Modify it to work on mac ARM chip

---

src/fosslight_source/_scan_item.py

Add .in and .po to the extensions list that is needed to be excluded

Add excluded extensions

---

src/fosslight_source/_help.py
src/fosslight_source/cli.py

Enable changing number of threads when calling SCANOSS using -c option.

Change SCANOSS thread using -c option

---

src/fosslight_source/_parsing_scancode_file_item.py
src/fosslight_source/_scan_item.py

Set is_license_text as True if file name matches with following regex.
['licen[cs]e[s]?', 'notice[s]?', 'legal', 'copyright[s]?', 'copying*', 'patent[s]?', 'unlicen[cs]e', 'eula','[a,l]?gpl[-]?[1-3]?[.,-,_]?[0-1]?', 'mit', 'bsd[-]?[0-4]?', 'bsd[-]?[0-4][-]?clause[s]?','apache[-,_]?[1-2]?[.,-,_]?[0-2]?']

Check notice file name for scancode

---

requirements.txt
src/fosslight_source/cli.py

Add detection summary message (cover sheet)

Add detection summary message (cover sheet)

---

src/fosslight_source/_scan_item.py

Limit the maximum number of characters in the license.
- Limit 200 per license.
- The license output to one cell is limited to 600.

Limit the maximum number of characters in the license

---

requirements.txt
src/fosslight_source/_help.py
src/fosslight_source/cli.py
src/fosslight_source/run_scancode.py
src/fosslight_source/run_scanoss.py
tox.ini

Enable multiple input for -f option.
Example 1)
Command : $fosslight_source **-o abc/output.xlsx -f csv excel**
Output
- abc/fosslight_log_src_YYMMDD_HHMM.txt
- abc/output.**csv**
- abc/output.**xlsx**
Example 2)
Command : $fosslight_source **-o abc/output.xlsx -f excel** -j
Output
- abc/fosslight_log_src_YYMMDD_HHMM.txt
- abc/output.**xlsx**
- abc/scancode_raw_result.json
- abc/scanner_output.wfp
- abc/scanoss_raw_result.json
Example 3)
Command : $fosslight_source **-o abc -f csv excel**
Output
- abc/fosslight_log_src_YYMMDD_HHMM.txt
- abc/fosslight_report_src_YYMMDD_HHMM.**csv**
- abc/fosslight_report_src_YYMMDD_HHMM.**xlsx**
Example 4)
Command : $fosslight_source **-f csv excel**
Output
- fosslight_log_src_YYMMDD_HHMM.txt
- fosslight_report_src_YYMMDD_HHMM.**csv**
- …

Enable multiple input for -f and -o option

---

src/fosslight_source/_scan_item.py

Check hidden files and mark 'Exlcude'.

Check hidden files and mark 'Exlcude'.

---

src/fosslight_source/run_scanoss.py

- Refactor to use SCANOSS library directly
- Remove deprecated pkg_resources usage
- #175

Change SCANOSS Invocation Method from Command Line to Library Function

---

requirements.txt
src/fosslight_source/_parsing_scancode_file_item.py
src/fosslight_source/_parsing_scanoss_file.py
src/fosslight_source/_scan_item.py
src/fosslight_source/cli.py
src/fosslight_source/run_scancode.py
tests/cli_test.py
tox.ini

Refactoring OSS Item

---

requirements.txt
src/fosslight_source/_parsing_scanoss_file.py
src/fosslight_source/_scan_item.py
src/fosslight_source/cli.py
src/fosslight_source/run_scancode.py
src/fosslight_source/run_scanoss.py
tests/cli_test.py

Support spdx

---

requirements.txt

This PR removes the following line from requirements.txt:
`typecode-libmagic;sys_platform!="darwin"`
Reason for removal:
The typecode-libmagic package was causing installation errors in our Docker environment. This dependency is not essential for the core functionality of our project and was leading to build failures.
Changes made:
Deleted the line specifying typecode-libmagic from requirements.txt
Impact:
Resolves Docker build failures related to this package
May affect file type detection capabilities in non-Darwin environments (if this feature was being used)
Next steps:
Monitor for any unintended side effects in file type detection (if applicable)
Consider alternative solutions for file type detection if needed in the future

Remove typecode-libmagic from requirements.txt

---

.github/workflows/pull-request.yml
requirements.txt

Fix the scancode ver for macos

Fix the scancode ver for macos

---

src/fosslight_source/cli.py
src/fosslight_source/run_scancode.py

- Print option name with error msg

Print option name with error msg

---

requirements.txt
src/fosslight_source/run_scanoss.py

Set the SCANOSS version to same or older then 1.14.0
Remove SCANOSS Raw file before scanning, if exist

Fix errors related to SCANOSS

---

requirements.txt
src/fosslight_source/cli.py

Fix exclude error with -e option

Fix exclude error

---

requirements.txt
src/fosslight_source/cli.py
src/fosslight_source/run_scanoss.py
tests/cli_test.py

change minimum SCANOSS version to 1.18.0
- Bug of SCANOSS being fixed.
- https://github.com/fosslight/fosslight_source_scanner/pull/198/commits/ed97e8ffaa66b57fdae3412c073036d68e05656b
- https://github.com/scanoss/scanoss.py/pull/76/commits/9fd0502c2110a1cff037863aafdc7adc3a253008#diff-54daea2ce27c020f5383bdfa0a0edc378f14f2990b693211ec652e38dcdf5094R527
Redirect SCANOSS output to log file

Update SCANOSS version and redirect log

---

.github/workflows/pull-request.yml

- Remove warning msg when install brew
- msg : 'openssl@3 3.4.1 is already installed and up-to-date. To reinstall 3.4.1, run: brew reinstall openssl@3'

Fix github action warning message

---

.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
requirements-dev.txt
requirements.txt
setup.py
src/fosslight_source/_scan_item.py
src/fosslight_source/cli.py

Update Python support to 3.10+ and remove scanners' version limit

Update Python support to 3.10+ and remove scanners' version limits

---

requirements.txt
src/fosslight_source/_parsing_scancode_file_item.py
src/fosslight_source/_parsing_scanoss_file.py
src/fosslight_source/_scan_item.py
src/fosslight_source/run_scancode.py

- Exclude package dirs with directory name
- Fix scancode-toolkit issue (https://github.com/aboutcode-org/scancode.io/pull/1796)

Exclude package dirs with directory name

---

src/fosslight_source/_parsing_scancode_file_item.py
src/fosslight_source/_scan_item.py

Add is_manifest_file field
